/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Caculator;

/**
 *
 * @author Diana Baez
 */
public class Calcu extends javax.swing.JFrame {

    /**
     * Creates new form Calcu
     */
     public double num1;
    public double num2;
    public String operador;
    public Calcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pantalla = new javax.swing.JLabel();
        BtnCE = new javax.swing.JButton();
        BtnRaiz = new javax.swing.JButton();
        BtnRetroseso = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        Siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        multiplica = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        masmenos = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Pantalla.setBackground(new java.awt.Color(102, 255, 153));
        Pantalla.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Pantalla.setForeground(new java.awt.Color(0, 0, 0));
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Pantalla.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnCE.setBackground(new java.awt.Color(255, 0, 0));
        BtnCE.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnCE.setForeground(new java.awt.Color(255, 255, 255));
        BtnCE.setText("CE");
        BtnCE.setSelected(true);
        BtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCEActionPerformed(evt);
            }
        });

        BtnRaiz.setBackground(new java.awt.Color(204, 204, 204));
        BtnRaiz.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnRaiz.setForeground(new java.awt.Color(0, 0, 0));
        BtnRaiz.setText("√");
        BtnRaiz.setSelected(true);
        BtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaizActionPerformed(evt);
            }
        });

        BtnRetroseso.setBackground(new java.awt.Color(204, 204, 204));
        BtnRetroseso.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BtnRetroseso.setForeground(new java.awt.Color(0, 0, 0));
        BtnRetroseso.setText("<=");
        BtnRetroseso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRetroseso.setSelected(true);
        BtnRetroseso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetrosesoActionPerformed(evt);
            }
        });

        dividir.setBackground(new java.awt.Color(204, 204, 204));
        dividir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        dividir.setForeground(new java.awt.Color(0, 0, 0));
        dividir.setText("/");
        dividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dividir.setSelected(true);
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        Siete.setBackground(new java.awt.Color(204, 204, 204));
        Siete.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Siete.setForeground(new java.awt.Color(0, 0, 0));
        Siete.setText("7");
        Siete.setSelected(true);
        Siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SieteActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(204, 204, 204));
        ocho.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ocho.setForeground(new java.awt.Color(0, 0, 0));
        ocho.setText("8");
        ocho.setSelected(true);
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(204, 204, 204));
        nueve.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        nueve.setForeground(new java.awt.Color(0, 0, 0));
        nueve.setText("9");
        nueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nueve.setSelected(true);
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        multiplica.setBackground(new java.awt.Color(204, 204, 204));
        multiplica.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        multiplica.setForeground(new java.awt.Color(0, 0, 0));
        multiplica.setText("X");
        multiplica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiplica.setSelected(true);
        multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(204, 204, 204));
        cuatro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cuatro.setForeground(new java.awt.Color(0, 0, 0));
        cuatro.setText("4");
        cuatro.setSelected(true);
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(204, 204, 204));
        cinco.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cinco.setForeground(new java.awt.Color(0, 0, 0));
        cinco.setText("5");
        cinco.setSelected(true);
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(204, 204, 204));
        seis.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        seis.setForeground(new java.awt.Color(0, 0, 0));
        seis.setText("6");
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seis.setSelected(true);
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        resta.setBackground(new java.awt.Color(204, 204, 204));
        resta.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        resta.setForeground(new java.awt.Color(0, 0, 0));
        resta.setText("-");
        resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resta.setSelected(true);
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        uno.setBackground(new java.awt.Color(204, 204, 204));
        uno.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        uno.setForeground(new java.awt.Color(0, 0, 0));
        uno.setText("1");
        uno.setSelected(true);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(204, 204, 204));
        dos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dos.setForeground(new java.awt.Color(0, 0, 0));
        dos.setText("2");
        dos.setSelected(true);
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(204, 204, 204));
        tres.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tres.setForeground(new java.awt.Color(0, 0, 0));
        tres.setText("3");
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tres.setSelected(true);
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        suma.setBackground(new java.awt.Color(204, 204, 204));
        suma.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        suma.setForeground(new java.awt.Color(0, 0, 0));
        suma.setText("+");
        suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suma.setSelected(true);
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        masmenos.setBackground(new java.awt.Color(204, 204, 204));
        masmenos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        masmenos.setForeground(new java.awt.Color(0, 0, 0));
        masmenos.setText("+/-");
        masmenos.setSelected(true);
        masmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masmenosActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(204, 204, 204));
        cero.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cero.setForeground(new java.awt.Color(0, 0, 0));
        cero.setText("0");
        cero.setSelected(true);
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(204, 204, 204));
        punto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        punto.setForeground(new java.awt.Color(0, 0, 0));
        punto.setText(".");
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setSelected(true);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(0, 153, 255));
        igual.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        igual.setForeground(new java.awt.Color(0, 0, 0));
        igual.setText("=");
        igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        igual.setSelected(true);
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRetroseso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Siete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(masmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRetroseso, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(dividir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueve, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(multiplica, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seis, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCEActionPerformed
        // TODO add your handling code here:
        Pantalla.setText("");
    }//GEN-LAST:event_BtnCEActionPerformed
 public String sincero(double resultado){
        String retorno = "";
        retorno = Double.toString(resultado);
        if(resultado%1 == 0){
            retorno = retorno.substring(0,retorno.length()-2);
        }
        return retorno;
    }
    private void BtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaizActionPerformed
        // TODO add your handling code here:
        this.num1 = Double.parseDouble(this.Pantalla.getText());
        this.Pantalla.setText(sincero(Math.sqrt(this.num1)));

        System.out.println(num1);
    }//GEN-LAST:event_BtnRaizActionPerformed

    private void BtnRetrosesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetrosesoActionPerformed
        // TODO add your handling code here:
        String cadena;
        cadena = this.Pantalla.getText();

        if(cadena.length()>0){
            cadena = cadena.substring(0, cadena.length()-1);
            this.Pantalla.setText(cadena);
        }
    }//GEN-LAST:event_BtnRetrosesoActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        // TODO add your handling code here:
        this.num1 = Double.parseDouble(this.Pantalla.getText());
        this.operador = "/";
        this.Pantalla.setText("");
    }//GEN-LAST:event_dividirActionPerformed

    private void SieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SieteActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+7);
    }//GEN-LAST:event_SieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+8);
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+9);
    }//GEN-LAST:event_nueveActionPerformed

    private void multiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaActionPerformed
        // TODO add your handling code here:
        this.num1 = Double.parseDouble(this.Pantalla.getText());
        this.operador = "*";
        this.Pantalla.setText("");
    }//GEN-LAST:event_multiplicaActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+4);
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+5);
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+6);
    }//GEN-LAST:event_seisActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // TODO add your handling code here:
        this.num1 = Double.parseDouble(this.Pantalla.getText());
        this.operador = "-";
        this.Pantalla.setText("");
    }//GEN-LAST:event_restaActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+1);
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+2);
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+3);
    }//GEN-LAST:event_tresActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
        this.num1 = Double.parseDouble(this.Pantalla.getText());
        this.operador = "+";
        this.Pantalla.setText("");
    }//GEN-LAST:event_sumaActionPerformed

    private void masmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masmenosActionPerformed
        // TODO add your handling code here:
        Double num;
        String cadena;

        cadena = this.Pantalla.getText();
        if(cadena.length()>0) {
            num = (-1)*Double.parseDouble(cadena);

            this.Pantalla.setText(sincero(num));
        }

    }//GEN-LAST:event_masmenosActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        // TODO add your handling code here:
        this.Pantalla.setText(this.Pantalla.getText()+0);
    }//GEN-LAST:event_ceroActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
        if(!(this.Pantalla.getText().contains("."))){
            this.Pantalla.setText(this.Pantalla.getText()+".");
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
        this.num2 = Double.parseDouble(this.Pantalla.getText());
        switch(this.operador){
            case "+":
            this.Pantalla.setText(sincero(this.num1+this.num2));
            break;
            case "-":
            this.Pantalla.setText(sincero(this.num1-this.num2));
            break;
            case "*":
            this.Pantalla.setText(sincero(this.num1*this.num2));
            break;
            case "/":
            if(this.num2 == 0){
                this.Pantalla.setText("No se divide entre Cero");
            }else{
                this.Pantalla.setText(sincero(this.num1-this.num2));
            }
            break;

        }
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCE;
    private javax.swing.JButton BtnRaiz;
    private javax.swing.JButton BtnRetroseso;
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton Siete;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dividir;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton masmenos;
    private javax.swing.JButton multiplica;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
